// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJoP4gcWVRGyAGsSOk9Qgg9HoDmPzm00',
    appId: '1:842913049513:android:cc5d5613b446aeae7df2b8',
    messagingSenderId: '842913049513',
    projectId: 'rrfx-50381',
    databaseURL: 'https://rrfx-50381-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rrfx-50381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzRHz5d1yL-MLdRZUNC1Rb7Ed-14XN3Jc',
    appId: '1:842913049513:ios:88b094b7f44f046c7df2b8',
    messagingSenderId: '842913049513',
    projectId: 'rrfx-50381',
    databaseURL: 'https://rrfx-50381-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rrfx-50381.firebasestorage.app',
    androidClientId: '842913049513-9cd84ju8dd9ducg4p20i7urfeqs7fng0.apps.googleusercontent.com',
    iosClientId: '842913049513-m6fb41tr7isqu61m1lh549pb4mh8rmlu.apps.googleusercontent.com',
    iosBundleId: 'com.rrfx.app',
  );

}